
name: deploy-myBlog
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # 手动构建
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: git clone
    - uses: actions/checkout@v4 #冲分支拉去代码
    - name: install nodejs
    - uses: actions/setup-node@v4  
      with:
        node-version: "14"
    - name: install yarn
    -  run: npm i yarn -g  -registry=https://registry.npm.taobao.org/
    - name: instal and build
    -  run: yarn  && yarn build
    - name: copy dist file with scp
    -  uses: appleboy/scp-action@v0.0.1
       with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "tests/a.txt,tests/b.txt"
        target: your_server_target_folder_path
