name: deploy-myBlog
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # 手动构建
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: git clone
      uses: actions/checkout@v4 #冲分支拉去代码
    - name: install nodejs
      uses: actions/setup-node@v4  
      with:
        node-version: "14"

    - name: instal
      run: npm i
    - name: build
      run: npm run build
    - name: copy dist file with scp
      uses: appleboy/scp-action@v0.0.1
      with: 
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        port: ${{ secrets.REMOTE_PORT }}
        source: ${{ secrets.REMOTE_SOURCE }}
        target: ${{ secrets.REMOTE_TARGET }}
